# Generated by Django 4.0.5 on 2022-07-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRequirements',
            new_name='RecipeRequirement',
        ),
    ]
